spring:
  profiles:
    active: local
  application:
    name: paymentcollection
  mvc:
    problemdetails:
      enabled: true
  elasticsearch:
    uris: http://localhost:9200
    # if security enabled:
    # username: elastic
    # password: changeme

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

