spring:
  profiles:
    active: local
  application:
    name: paymentcollection
  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false